deps:
# COMMON
- name: pmm
  branch: PMM-2.0
  path: sources/pmm/src/github.com/percona/pmm
  url: https://github.com/percona/pmm
  component: common
# CLIENT
- name: pmm-admin
  branch: master
  path: sources/pmm-admin/src/github.com/percona/pmm-admin
  url: https://github.com/percona/pmm-admin.git
  component: client
- name: pmm-agent
  branch: master
  path: sources/pmm-agent/src/github.com/percona/pmm-agent
  url: https://github.com/percona/pmm-agent.git
  component: client
- name: node_exporter
  branch: main
  path: sources/node_exporter/src/github.com/prometheus/node_exporter
  url: https://github.com/percona/node_exporter.git
  component: client
- name: mysqld_exporter
  branch: master
  path: sources/mysqld_exporter/src/github.com/percona/mysqld_exporter
  url: https://github.com/percona/mysqld_exporter.git
  component: client
- name: mongodb_exporter
  branch: release-0.20.5
  path: sources/mongodb_exporter/src/github.com/percona/mongodb_exporter
  url: https://github.com/percona/mongodb_exporter.git
  component: client
- name: postgres_exporter
  branch: master
  path: sources/postgres_exporter/src/github.com/percona/postgres_exporter
  url: https://github.com/percona/postgres_exporter
  component: client
- name: clickhouse_exporter
  branch: master
  path: sources/clickhouse_exporter/src/github.com/Percona-Lab/clickhouse_exporter
  url: https://github.com/Percona-Lab/clickhouse_exporter
  component: client
- name: proxysql_exporter
  branch: main
  path: sources/proxysql_exporter/src/github.com/percona/proxysql_exporter
  url: https://github.com/percona/proxysql_exporter.git
  component: client
- name: rds_exporter
  branch: master
  path: sources/rds_exporter/src/github.com/percona/rds_exporter
  url: https://github.com/percona/rds_exporter
  component: client
  default_branch: master
- name: azure_metrics_exporter
  branch: master
  path: sources/azure_metrics_exporter/src/github.com/percona/azure_metrics_exporter
  url: https://github.com/percona/azure_metrics_exporter
  component: client
  default_branch: master
- name: percona-toolkit
  branch: release-3.2.1
  path: sources/percona-toolkit/src/github.com/percona/percona-toolkit
  url: https://github.com/percona/percona-toolkit.git
  component: client
  default_branch: release-3.2.1
# SERVER
- name: pmm-managed
  branch: PMM-2.0
  path: sources/pmm-managed/src/github.com/percona/pmm-managed
  url: https://github.com/percona/pmm-managed
  component: server
  default_branch: PMM-2.0
- name: dbaas-controller
  branch: main
  path: sources/dbaas-controller/src/github.com/percona-platform/dbaas-controller
  url: https://github.com/percona-platform/dbaas-controller
  component: server
  default_branch: main
- name: qan-api2
  branch: master
  path: sources/qan-api2/src/github.com/percona/qan-api2
  url: https://github.com/percona/qan-api2
  component: server
  default_branch: master
- name: pmm-update
  branch: PMM-2.0
  path: sources/pmm-update/src/github.com/percona/pmm-update
  url: https://github.com/percona/pmm-update
  component: server
  default_branch: PMM-2.0
- name: pmm-server
  branch: PMM-2.0
  path: sources/pmm-server
  url: https://github.com/percona/pmm-server
  component: server
  default_branch: PMM-2.0
- name: grafana-dashboards
  branch: PMM-2.0
  path: sources/grafana-dashboards
  url: https://github.com/percona/grafana-dashboards
  component: server
  default_branch: PMM-2.0
- name: grafana
  branch: master
  path: sources/grafana/src/github.com/grafana/grafana
  url: https://github.com/percona-platform/grafana
  component: server
  default_branch: master
# QA
- name: pmm-api-tests
  branch: master
  path: sources/pmm-api-tests/src/github.com/Percona-Lab/pmm-api-tests
  url: https://github.com/Percona-Lab/pmm-api-tests
  component: qa
  default_branch: master
- name: pmm-qa
  branch: master
  path: sources/pmm-qa/src/github.com/percona/pmm-qa
  url: https://github.com/percona/pmm-qa
  component: qa
  default_branch: master
- name: pmm-ui-tests
  branch: main
  path: sources/pmm-ui-tests/src/github.com/percona/pmm-ui-tests
  url: https://github.com/percona/pmm-ui-tests
  component: qa
  default_branch: main
